# Generated by Django 6.0.6 on 2026-06-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=100, unique=True, verbose_name="Email"),
                ),
                ("fullname", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель сообщения",
                "verbose_name_plural": "Получатели сообщения",
                "ordering": ["fullname"],
            },
        ),
    ]
