# Generated by Django 6.0.6 on 2026-08-09 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagesender", "0002_message_sending"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(verbose_name="Дата и время попытки"),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Статус")),
                (
                    "server_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "sending",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending",
                        to="messagesender.sending",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
