# Generated by Django 6.0.6 on 2026-08-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messagesender", "0003_sendinglog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sending",
            options={
                "ordering": ["message"],
                "permissions": [
                    ("can_view_others_sendings", "Can view others sendings")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
